package org.micromanager.ScanPlugin;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import mmcorej.CMMCore;
import org.micromanager.MultiStagePosition;
import org.micromanager.internal.MMStudio;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raghu
 */
public class ContScanFrame extends javax.swing.JFrame {
    private static MMStudio mm_;
    private final CMMCore core_;
    private ScanSettings acquisitionSettings;
    private final HardwareCommands hardwareCommands;
    private int regionNum;
    private String directory;
    private MultiStagePosition region;
    private double zStart;
    private double zEnd;
    private double xPos;
    private Double yPos;
    private Double zPos;
    private Acquisition acquisition;
    /**
     * Creates new form ContScanFrame
     */
    public ContScanFrame(MMStudio studio) {
        mm_ = (MMStudio) studio;
        core_ = mm_.core();
        hardwareCommands = new HardwareCommands(mm_);
        acquisitionSettings = new ScanSettings(mm_);
        regionNum = 0;
        directory = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        startTitle = new javax.swing.JLabel();
        startDescription = new javax.swing.JLabel();
        setupComboBox = new javax.swing.JComboBox<>();
        beginButton = new javax.swing.JButton();
        regionsPanel = new javax.swing.JPanel();
        regionTitle = new javax.swing.JLabel();
        regionLabel = new javax.swing.JLabel();
        goToButton = new javax.swing.JButton();
        SetButton = new javax.swing.JButton();
        xLabel = new javax.swing.JLabel();
        xField = new javax.swing.JTextField();
        yLabel = new javax.swing.JLabel();
        yField = new javax.swing.JTextField();
        zField = new javax.swing.JTextField();
        zLabel = new javax.swing.JLabel();
        previousRegionButton = new javax.swing.JButton();
        toAcquisitionButton = new javax.swing.JButton();
        nextRegionButton = new javax.swing.JButton();
        acquisitionPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        zSetupLabel = new javax.swing.JLabel();
        channelsLabel = new javax.swing.JLabel();
        regionLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        channelComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allChannelJList = new javax.swing.JList<>();
        addChannelButton = new javax.swing.JButton();
        removeChannelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        usedChannelJList = new javax.swing.JList<>();
        moveUpButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();
        zStartSetButton = new javax.swing.JButton();
        zStartLabel = new javax.swing.JLabel();
        zEndLabel = new javax.swing.JLabel();
        zEndSetButton = new javax.swing.JButton();
        zEndField = new javax.swing.JTextField();
        zStartField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        stepSizeBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        directoryBox = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        startAcquisitionButton = new javax.swing.JButton();
        backToRegionSetupButton = new javax.swing.JButton();
        SaveLocationLabel = new javax.swing.JLabel();
        brightFieldCheck = new javax.swing.JCheckBox();
        timePointsCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        intervalField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        timePointsField = new javax.swing.JTextField();

        mainPanel.setLayout(new java.awt.CardLayout());

        startTitle.setText("Continuous Scan Plugin");

        startDescription.setText("This plugin is used for continuous stage motion scans. Choose HTLS or CLS and click \"Begin.\"");

        setupComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLS", "HTLS" }));
        setupComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupComboBoxActionPerformed(evt);
            }
        });

        beginButton.setText("Begin");
        beginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(startTitle))
                    .addComponent(startDescription)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(beginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(startTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beginButton)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        mainPanel.add(startPanel, "startPanel");

        regionTitle.setText("Region Setup");

        regionLabel.setText("Region" + (regionNum + 1));

        goToButton.setText("Go To");
        if (acquisitionSettings.getPositionList().getPosition(regionNum) == null) {
            goToButton.setEnabled(false);
        }
        goToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToButtonActionPerformed(evt);
            }
        });

        SetButton.setText("Set as current Stage Position");
        SetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetButtonActionPerformed(evt);
            }
        });

        xLabel.setText("X:");

        xField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xFieldKeyReleased(evt);
            }
        });

        yLabel.setText("Y:");

        yField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yFieldKeyReleased(evt);
            }
        });

        zField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zFieldKeyReleased(evt);
            }
        });

        zLabel.setText("Z:");

        previousRegionButton.setText("Previous Region");
        if (regionNum < 1) {
            previousRegionButton.setEnabled(false);
        }
        previousRegionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousRegionButtonActionPerformed(evt);
            }
        });

        toAcquisitionButton.setText("Finish");
        if (acquisitionSettings.getPositionList().getNumberOfPositions() == 0) {
            toAcquisitionButton.setEnabled(false);
        }
        toAcquisitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAcquisitionButtonActionPerformed(evt);
            }
        });

        nextRegionButton.setText("Next Region");
        if (regionNum < 1) {
            nextRegionButton.setEnabled(false);
        }
        nextRegionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextRegionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regionsPanelLayout = new javax.swing.GroupLayout(regionsPanel);
        regionsPanel.setLayout(regionsPanelLayout);
        regionsPanelLayout.setHorizontalGroup(
            regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regionsPanelLayout.createSequentialGroup()
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regionsPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regionsPanelLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(yLabel)
                                    .addComponent(zLabel)
                                    .addComponent(xLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(goToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(regionsPanelLayout.createSequentialGroup()
                                .addComponent(previousRegionButton)
                                .addGap(18, 18, 18)
                                .addComponent(toAcquisitionButton)
                                .addGap(18, 18, 18)
                                .addComponent(nextRegionButton))
                            .addGroup(regionsPanelLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(regionLabel)
                                    .addComponent(regionTitle)))))
                    .addGroup(regionsPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(SetButton)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        regionsPanelLayout.setVerticalGroup(
            regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regionTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regionLabel)
                .addGap(25, 25, 25)
                .addComponent(goToButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zLabel))
                .addGap(18, 18, 18)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toAcquisitionButton)
                    .addComponent(previousRegionButton)
                    .addComponent(nextRegionButton))
                .addContainerGap(363, Short.MAX_VALUE))
        );

        mainPanel.add(regionsPanel, "regionsPanel");

        titleLabel.setText("Acquisition Setup");

        zSetupLabel.setText("Z-stack Setup");

        channelsLabel.setText("Channels");

        regionLabel1.setText("Region 1");

        jLabel3.setText("Available");

        channelComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(core_.getAvailableConfigGroups().toArray()));
        channelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Used");

        DefaultListModel allChannelModel = new DefaultListModel();
        allChannelModel.addAll(Arrays.asList(core_.getAvailableConfigs((String) channelComboBox.getSelectedItem()).toArray()));
        allChannelJList.setModel(allChannelModel);
        jScrollPane1.setViewportView(allChannelJList);

        addChannelButton.setText("Add >>");
        addChannelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChannelButtonActionPerformed(evt);
            }
        });

        removeChannelButton.setText("<< Remove");
        removeChannelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeChannelButtonActionPerformed(evt);
            }
        });

        usedChannelJList.setModel(new DefaultListModel<String>() {
        });
        jScrollPane2.setViewportView(usedChannelJList);

        moveUpButton.setText("Move Up");
        moveUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpButtonActionPerformed(evt);
            }
        });

        moveDownButton.setText("Move Down");
        moveDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownButtonActionPerformed(evt);
            }
        });

        zStartSetButton.setText("Set");
        zStartSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zStartSetButtonActionPerformed(evt);
            }
        });

        zStartLabel.setText("Z-Start:");

        zEndLabel.setText("Z-End:");

        zEndSetButton.setText("Set");
        zEndSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zEndSetButtonActionPerformed(evt);
            }
        });

        zEndField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zEndFieldKeyReleased(evt);
            }
        });

        zStartField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zStartFieldKeyReleased(evt);
            }
        });

        nextButton.setText("Next Region");
        if (acquisitionSettings.getScanStartPositionArray().size() <= regionNum) {
            nextButton.setEnabled(false);
        }
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous Region");
        previousButton.setEnabled(false);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Step Size:");

        stepSizeBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stepSizeBox.setText(String.valueOf(acquisitionSettings.stepSize));
        stepSizeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepSizeBoxActionPerformed(evt);
            }
        });
        stepSizeBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stepSizeBoxKeyReleased(evt);
            }
        });

        jLabel2.setText("um");

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        startAcquisitionButton.setText("Start Acquisition");
        startAcquisitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAcquisitionButtonActionPerformed(evt);
            }
        });

        backToRegionSetupButton.setText("Back To Region Setup");
        backToRegionSetupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToRegionSetupButtonActionPerformed(evt);
            }
        });

        SaveLocationLabel.setText("Save Location");

        brightFieldCheck.setText("Bright Field Image?");
        brightFieldCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brightFieldCheckActionPerformed(evt);
            }
        });

        timePointsCheck.setText("Time Points");
        timePointsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timePointsCheckActionPerformed(evt);
            }
        });

        jLabel5.setText("Interval (in seconds) :");

        if (timePointsCheck.isSelected()) {
            intervalField.setEnabled(true);
        }

        else {
            intervalField.setEnabled(false);
        }
        intervalField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                intervalFieldKeyReleased(evt);
            }
        });

        jLabel6.setText("Number of Time Points:");

        if (timePointsCheck.isSelected()) {
            timePointsField.setEnabled(true);
        }

        else {
            timePointsField.setEnabled(false);
        }
        timePointsField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                timePointsFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout acquisitionPanelLayout = new javax.swing.GroupLayout(acquisitionPanel);
        acquisitionPanel.setLayout(acquisitionPanelLayout);
        acquisitionPanelLayout.setHorizontalGroup(
            acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(directoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseButton)
                .addGap(96, 96, 96))
            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                            .addComponent(previousButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nextButton))
                                        .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(zEndLabel)
                                                .addComponent(zStartLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                                    .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(zStartSetButton)
                                                        .addComponent(zEndSetButton))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(zEndField)
                                                        .addComponent(zStartField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(brightFieldCheck))
                                            .addGap(30, 30, 30)))
                                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(timePointsCheck)
                                            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(stepSizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)))))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(regionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(zSetupLabel))
                                .addGap(108, 108, 108)))
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removeChannelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moveDownButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moveUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addChannelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(channelsLabel)
                                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(59, 59, 59)
                                        .addComponent(channelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                        .addComponent(startAcquisitionButton)
                        .addGap(188, 188, 188))))
            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(SaveLocationLabel))
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(titleLabel))
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(backToRegionSetupButton))
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(intervalField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(timePointsField))))
                .addContainerGap())
        );
        acquisitionPanelLayout.setVerticalGroup(
            acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addComponent(channelsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(channelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(5, 5, 5))
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addComponent(zSetupLabel)
                        .addGap(9, 9, 9)
                        .addComponent(regionLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2)
                        .addGroup(acquisitionPanelLayout.createSequentialGroup()
                            .addComponent(addChannelButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removeChannelButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveUpButton)
                            .addGap(4, 4, 4)
                            .addComponent(moveDownButton)))
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(brightFieldCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zStartSetButton)
                            .addComponent(zStartLabel)
                            .addComponent(zStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zEndLabel)
                            .addComponent(zEndSetButton)
                            .addComponent(zEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousButton)
                            .addComponent(nextButton))
                        .addGap(18, 18, 18)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stepSizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(44, 44, 44)
                .addComponent(timePointsCheck)
                .addGap(25, 25, 25)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(timePointsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(intervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(SaveLocationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browseButton)
                    .addComponent(directoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startAcquisitionButton)
                    .addComponent(backToRegionSetupButton))
                .addGap(27, 27, 27))
        );

        mainPanel.add(acquisitionPanel, "acquisitionPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setupComboBoxActionPerformed

    private void beginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginButtonActionPerformed
        //REMINDER ADD BACK PIXEL CALIBRATION
        if ((String)setupComboBox.getSelectedItem() == "HTLS"){
            try {
            } catch (Exception ex) {
                Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ((String)setupComboBox.getSelectedItem() == "CLS") {
            try {
            } catch (Exception ex) {
                Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        regionNum = 0;
        regionLabel.setText("Region " + 1);
        xField.setText("");
        yField.setText("");
        zField.setText("");
        
        zStartField.setText("");
        zEndField.setText("");
        regionLabel1.setText("Region " + 1);
        
        timePointsField.setText("");
        intervalField.setText("");
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "regionsPanel");
    }//GEN-LAST:event_beginButtonActionPerformed

    private void goToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToButtonActionPerformed
        MultiStagePosition region = acquisitionSettings.getPositionList().getPosition(regionNum);
        if (region != null) {
            try {
                hardwareCommands.moveStage(region);
            } catch (Exception ex) {
                Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_goToButtonActionPerformed

    private void SetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetButtonActionPerformed
        try {
            region = hardwareCommands.getStagePosition();
            acquisitionSettings.setRegion(regionNum, region);
            acquisitionSettings.setXPosition(regionNum, region.getX());
            acquisitionSettings.setYPosition(regionNum, region.getY());
            acquisitionSettings.setZPosition(regionNum, region.getZ());
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        xField.setText(String.valueOf(region.getX()));
        yField.setText(String.valueOf(region.getY()));
        zField.setText(String.valueOf(region.getZ()));

        toAcquisitionButton.setEnabled(true);
        nextRegionButton.setEnabled(true);
        goToButton.setEnabled(true);
    }//GEN-LAST:event_SetButtonActionPerformed

    private void previousRegionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousRegionButtonActionPerformed
        regionNum--;
        
        MultiStagePosition region = acquisitionSettings.getPositionList().getPosition(regionNum);
        xField.setText(String.valueOf(region.getX()));
        yField.setText(String.valueOf(region.getY()));
        zField.setText(String.valueOf(region.getZ()));
        regionLabel.setText("Region" + (regionNum + 1));
        
        if (regionNum == 0) {
            previousRegionButton.setEnabled(false);
        }
        goToButton.setEnabled(true);
        nextRegionButton.setEnabled(true);
    }//GEN-LAST:event_previousRegionButtonActionPerformed

    private void toAcquisitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAcquisitionButtonActionPerformed
        regionNum = 0;
        
        acquisitionSettings.initializeBrightFieldArray();
        brightFieldCheck.setSelected(acquisitionSettings.getBrightFieldArray().get(0));
        
        try {
            hardwareCommands.moveStage(acquisitionSettings.getPositionList().getPosition(regionNum));
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        regionLabel1.setText("Region " + (regionNum + 1));
        
        if (acquisitionSettings.getScanStartPositionArray().size() > regionNum) {
            zStartField.setText(String.valueOf(acquisitionSettings.getScanStartPositionArray().get(regionNum)));
        }
        
        if (acquisitionSettings.getScanEndPositionArray().size() > regionNum) {
            zEndField.setText(String.valueOf(acquisitionSettings.getScanEndPositionArray().get(regionNum)));
        }
        
        previousButton.setEnabled(false);
        
        if (acquisitionSettings.getScanEndPositionArray().size() >= 1 & acquisitionSettings.getScanStartPositionArray().size() >= 1) {
            nextButton.setEnabled(true);
        }
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "acquisitionPanel");
    }//GEN-LAST:event_toAcquisitionButtonActionPerformed

    private void nextRegionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextRegionButtonActionPerformed
        regionNum++;
        
        if (acquisitionSettings.getPositionList().getPosition(regionNum) != null) {
            MultiStagePosition region = acquisitionSettings.getPositionList().getPosition(regionNum);
            xField.setText(String.valueOf(region.getX()));
            yField.setText(String.valueOf(region.getY()));
            zField.setText(String.valueOf(region.getZ()));
        }
        else {
            nextRegionButton.setEnabled(false);
            goToButton.setEnabled(false);
            xField.setText("");
            yField.setText("");
            zField.setText("");
        }
        regionLabel.setText("Region" + (regionNum + 1));
        previousRegionButton.setEnabled(true);
    }//GEN-LAST:event_nextRegionButtonActionPerformed

    private void channelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelComboBoxActionPerformed
        DefaultListModel allModel = (DefaultListModel) allChannelJList.getModel();
        allModel.removeAllElements();
        allModel.addAll(Arrays.asList(core_.getAvailableConfigs((String) channelComboBox.getSelectedItem()).toArray()));
        allChannelJList.setModel(allModel);

        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();
        usedModel.removeAllElements();
        usedChannelJList.setModel(usedModel);
    }//GEN-LAST:event_channelComboBoxActionPerformed

    private void addChannelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChannelButtonActionPerformed
        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();
        List<String> selectedList = allChannelJList.getSelectedValuesList();
        usedModel.addAll(selectedList);
        usedChannelJList.setModel(usedModel);

        DefaultListModel allModel =  (DefaultListModel) allChannelJList.getModel();
        for (int i=0; i < selectedList.size(); i++) {
            allModel.removeElement(selectedList.get(i));
        }
        allChannelJList.setModel(allModel);
    }//GEN-LAST:event_addChannelButtonActionPerformed

    private void removeChannelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeChannelButtonActionPerformed
        DefaultListModel allModel = (DefaultListModel) allChannelJList.getModel();
        List<String> selectedList = usedChannelJList.getSelectedValuesList();
        allModel.addAll(selectedList);
        allChannelJList.setModel(allModel);

        DefaultListModel usedModel =  (DefaultListModel) usedChannelJList.getModel();
        for (int i=0; i < selectedList.size(); i++) {
            usedModel.removeElement(selectedList.get(i));
        }
        usedChannelJList.setModel(usedModel);
    }//GEN-LAST:event_removeChannelButtonActionPerformed

    private void moveUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpButtonActionPerformed
        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();

        String movedChannel = usedChannelJList.getSelectedValue();
        int movedChannelIndex = usedChannelJList.getSelectedIndex();

        int channelAboveIndex = movedChannelIndex - 1;
        String channelAbove = (String) usedModel.getElementAt(channelAboveIndex);

        usedModel.setElementAt(channelAbove, movedChannelIndex);
        usedModel.setElementAt(movedChannel, channelAboveIndex);
        usedChannelJList.setModel(usedModel);
    }//GEN-LAST:event_moveUpButtonActionPerformed

    private void moveDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownButtonActionPerformed
        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();

        String movedChannel = usedChannelJList.getSelectedValue();
        int movedChannelIndex = usedChannelJList.getSelectedIndex();

        int channelBelowIndex = movedChannelIndex + 1;
        String channelBelow = (String) usedModel.getElementAt(channelBelowIndex);

        usedModel.setElementAt(channelBelow, movedChannelIndex);
        usedModel.setElementAt(movedChannel, channelBelowIndex);
        usedChannelJList.setModel(usedModel);
    }//GEN-LAST:event_moveDownButtonActionPerformed

    private void zStartSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zStartSetButtonActionPerformed
        try {
            zStart = hardwareCommands.getZPosition();
            acquisitionSettings.setScanStartPosition(zStart, regionNum);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        zStartField.setText(String.valueOf(acquisitionSettings.getScanStartPositionArray().get(regionNum)));
        
        if (acquisitionSettings.getScanStartPositionArray().size() > regionNum & 
            acquisitionSettings.getScanEndPositionArray().size() > regionNum &
            acquisitionSettings.getPositionList().getNumberOfPositions() > regionNum + 1) {
            
            nextButton.setEnabled(true);
        }
    }//GEN-LAST:event_zStartSetButtonActionPerformed

    private void zEndSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zEndSetButtonActionPerformed
        try {
            zEnd = hardwareCommands.getZPosition();
            acquisitionSettings.setScanEndPosition(zEnd, regionNum);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        zEndField.setText(String.valueOf(acquisitionSettings.getScanEndPositionArray().get(regionNum)));
        
        if (acquisitionSettings.getScanStartPositionArray().size() > regionNum & 
            acquisitionSettings.getScanEndPositionArray().size() > regionNum &
            acquisitionSettings.getPositionList().getNumberOfPositions() > regionNum + 1) {
            
            nextButton.setEnabled(true);
        }
    }//GEN-LAST:event_zEndSetButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        regionNum++;

        MultiStagePosition region = acquisitionSettings.getPositionList().getPosition(regionNum);
        
        try {
            hardwareCommands.moveStage(region);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        regionLabel1.setText("Region " + (regionNum + 1));
        previousButton.setEnabled(true);
        
        //Insures that if there isn't a next region to go to, nextButton is disabled
        if (acquisitionSettings.getPositionList().getNumberOfPositions() == regionNum + 1) {
            nextButton.setEnabled(false);
        }
        
        //Insures that the zFields are correctly filled when nextButton is pressed
        if (acquisitionSettings.getScanStartPositionArray().size() > regionNum) {
            zStartField.setText(String.valueOf(acquisitionSettings.getScanStartPositionArray().get(regionNum)));
        }
        if (acquisitionSettings.getScanEndPositionArray().size() > regionNum) {
            zEndField.setText(String.valueOf(acquisitionSettings.getScanEndPositionArray().get(regionNum)));
        }   
        if (acquisitionSettings.getScanStartPositionArray().size() <= regionNum) {
            zStartField.setText("");
        }
        if (acquisitionSettings.getScanEndPositionArray().size() <= regionNum) {
            zEndField.setText("");
        }
        
        brightFieldCheck.setSelected(acquisitionSettings.getBrightFieldArray().get(regionNum));
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        regionNum--;

        MultiStagePosition region = acquisitionSettings.getPositionList().getPosition(regionNum);
        
        try {
            hardwareCommands.moveStage(region);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        regionLabel1.setText("Region" + (regionNum + 1));
        nextButton.setEnabled(true);
        
        zStartField.setText(String.valueOf(acquisitionSettings.getScanStartPositionArray().get(regionNum)));
        zEndField.setText(String.valueOf(acquisitionSettings.getScanEndPositionArray().get(regionNum)));

        if (regionNum == 0) {
            previousButton.setEnabled(false);
        }
        
        brightFieldCheck.setSelected(acquisitionSettings.getBrightFieldArray().get(regionNum));
    }//GEN-LAST:event_previousButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.showSaveDialog(null);
        directory = fileChooser.getSelectedFile().getPath();
        directoryBox.setText(directory);
        directory.replace('\\','/');
    }//GEN-LAST:event_browseButtonActionPerformed

    private void startAcquisitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAcquisitionButtonActionPerformed
        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();
        acquisitionSettings.channelGroupName = (String) channelComboBox.getSelectedItem();
        
        for (int i=0; i < usedModel.getSize(); i++) {
            String channel = (String) usedModel.getElementAt(i);
            acquisitionSettings.addChannel(channel);
        }
        
        //this.setVisible(false);
        //CardLayout card = (CardLayout)mainPanel.getLayout();
        //card.show(mainPanel, "startPanel");
        //regionNum = 0;
        //this.dispose();
        
        System.out.println("DOG1");
        acquisition = new Acquisition(acquisitionSettings, directory, mm_);
        System.out.println("DOG2");
        try {
            System.out.println("DOG3");
            acquisition.startAcquisition();
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_startAcquisitionButtonActionPerformed

    private void backToRegionSetupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToRegionSetupButtonActionPerformed
        regionNum = 0;
        
        regionLabel.setText("Region " + (regionNum + 1));
        
        xField.setText(String.valueOf(acquisitionSettings.getPositionList().getPosition(regionNum).getX()));
        yField.setText(String.valueOf(acquisitionSettings.getPositionList().getPosition(regionNum).getY()));
        zField.setText(String.valueOf(acquisitionSettings.getPositionList().getPosition(regionNum).getZ()));
        
        if (regionNum == 0) {
            previousRegionButton.setEnabled(false);
        }
        
        nextRegionButton.setEnabled(true);
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "regionsPanel");
    }//GEN-LAST:event_backToRegionSetupButtonActionPerformed

    private void brightFieldCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brightFieldCheckActionPerformed
        if (brightFieldCheck.isSelected()) {
            acquisitionSettings.setBrightFieldArrayElement(true, regionNum);
        }
        else {
            acquisitionSettings.setBrightFieldArrayElement(false, regionNum);
        };
            
    }//GEN-LAST:event_brightFieldCheckActionPerformed

    private void timePointsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timePointsCheckActionPerformed
        if (timePointsCheck.isSelected()) {
            acquisitionSettings.timePointsBoolean = true;
            intervalField.setEnabled(true);
            timePointsField.setEnabled(true);
        }
        else {
            acquisitionSettings.timePointsBoolean = false;
            intervalField.setEnabled(false);
            timePointsField.setEnabled(false);
        }
    }//GEN-LAST:event_timePointsCheckActionPerformed

    private void xFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xFieldKeyReleased
        xPos = Double.valueOf(xField.getText());
        
        acquisitionSettings.setXPosition(regionNum, xPos);
        
        if (acquisitionSettings.getXPositionArray().size() > regionNum &
            acquisitionSettings.getYPositionArray().size() > regionNum &
            acquisitionSettings.getZPositionArray().size() > regionNum ) {
            
            double yPos = acquisitionSettings.getYPositionArray().get(regionNum);
            double zPos = acquisitionSettings.getZPositionArray().get(regionNum);
            acquisitionSettings.setRegion(regionNum, xPos, yPos, zPos);
            goToButton.setEnabled(true);
            nextRegionButton.setEnabled(true);
            toAcquisitionButton.setEnabled(true);
        }   
    }//GEN-LAST:event_xFieldKeyReleased

    private void yFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yFieldKeyReleased
        yPos = Double.valueOf(yField.getText());
        
        acquisitionSettings.setYPosition(regionNum, yPos);
        
        if (acquisitionSettings.getXPositionArray().size() > regionNum &
            acquisitionSettings.getYPositionArray().size() > regionNum &
            acquisitionSettings.getZPositionArray().size() > regionNum ) {
            
            double xPos = acquisitionSettings.getXPositionArray().get(regionNum);
            double zPos = acquisitionSettings.getZPositionArray().get(regionNum);
            acquisitionSettings.setRegion(regionNum, xPos, yPos, zPos);
            goToButton.setEnabled(true);
            nextRegionButton.setEnabled(true);
            toAcquisitionButton.setEnabled(true);
        }
    }//GEN-LAST:event_yFieldKeyReleased

    private void zFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zFieldKeyReleased
        zPos = Double.valueOf(zField.getText());
        
        acquisitionSettings.setZPosition(regionNum, zPos);
        
        if (acquisitionSettings.getXPositionArray().size() > regionNum &
            acquisitionSettings.getYPositionArray().size() > regionNum &
            acquisitionSettings.getZPositionArray().size() > regionNum ) {
            
            double xPos = acquisitionSettings.getXPositionArray().get(regionNum);
            double yPos = acquisitionSettings.getYPositionArray().get(regionNum);
            acquisitionSettings.setRegion(regionNum, xPos, yPos, zPos);
            goToButton.setEnabled(true);
            nextRegionButton.setEnabled(true);
            toAcquisitionButton.setEnabled(true);
        }
    }//GEN-LAST:event_zFieldKeyReleased

    private void zStartFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zStartFieldKeyReleased
        zStart = Double.valueOf(zStartField.getText());

        acquisitionSettings.setScanStartPosition(zStart, regionNum);

        
        if (acquisitionSettings.getScanStartPositionArray().size() > regionNum & 
            acquisitionSettings.getScanEndPositionArray().size() > regionNum &
            acquisitionSettings.getPositionList().getNumberOfPositions() > regionNum + 1) {
            
            nextButton.setEnabled(true);
        }
    }//GEN-LAST:event_zStartFieldKeyReleased

    private void zEndFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zEndFieldKeyReleased
        zEnd = Double.valueOf(zEndField.getText());
        
        acquisitionSettings.setScanEndPosition(zEnd, regionNum);

        
        if (acquisitionSettings.getScanStartPositionArray().size() > regionNum & 
            acquisitionSettings.getScanEndPositionArray().size() > regionNum &
            acquisitionSettings.getPositionList().getNumberOfPositions() > regionNum + 1) {
            
            nextButton.setEnabled(true);
        }
    }//GEN-LAST:event_zEndFieldKeyReleased

    private void timePointsFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_timePointsFieldKeyReleased
        acquisitionSettings.numTimePoints = (int) Math.round(Double.valueOf(timePointsField.getText()));
    }//GEN-LAST:event_timePointsFieldKeyReleased

    private void intervalFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_intervalFieldKeyReleased
        acquisitionSettings.timePointsInterval = (int) Math.round(Double.valueOf(intervalField.getText()));
    }//GEN-LAST:event_intervalFieldKeyReleased

    private void stepSizeBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stepSizeBoxKeyReleased
        acquisitionSettings.stepSize = (int) Math.round(Double.valueOf(stepSizeBox.getText()));
    }//GEN-LAST:event_stepSizeBoxKeyReleased

    private void stepSizeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepSizeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stepSizeBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContScanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContScanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContScanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContScanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContScanFrame(mm_).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SaveLocationLabel;
    private javax.swing.JButton SetButton;
    private javax.swing.JPanel acquisitionPanel;
    private javax.swing.JButton addChannelButton;
    private javax.swing.JList<String> allChannelJList;
    private javax.swing.JButton backToRegionSetupButton;
    private javax.swing.JButton beginButton;
    private javax.swing.JCheckBox brightFieldCheck;
    private javax.swing.JButton browseButton;
    private javax.swing.JComboBox<String> channelComboBox;
    private javax.swing.JLabel channelsLabel;
    private javax.swing.JTextField directoryBox;
    private javax.swing.JButton goToButton;
    private javax.swing.JTextField intervalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveUpButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextRegionButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton previousRegionButton;
    private javax.swing.JLabel regionLabel;
    private javax.swing.JLabel regionLabel1;
    private javax.swing.JLabel regionTitle;
    private javax.swing.JPanel regionsPanel;
    private javax.swing.JButton removeChannelButton;
    private javax.swing.JComboBox<String> setupComboBox;
    private javax.swing.JButton startAcquisitionButton;
    private javax.swing.JLabel startDescription;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel startTitle;
    private javax.swing.JTextField stepSizeBox;
    private javax.swing.JCheckBox timePointsCheck;
    private javax.swing.JTextField timePointsField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toAcquisitionButton;
    private javax.swing.JList<String> usedChannelJList;
    private javax.swing.JTextField xField;
    private javax.swing.JLabel xLabel;
    private javax.swing.JTextField yField;
    private javax.swing.JLabel yLabel;
    private javax.swing.JTextField zEndField;
    private javax.swing.JLabel zEndLabel;
    private javax.swing.JButton zEndSetButton;
    private javax.swing.JTextField zField;
    private javax.swing.JLabel zLabel;
    private javax.swing.JLabel zSetupLabel;
    private javax.swing.JTextField zStartField;
    private javax.swing.JLabel zStartLabel;
    private javax.swing.JButton zStartSetButton;
    // End of variables declaration//GEN-END:variables
}
