package org.micromanager.ScanPlugin;

import java.awt.CardLayout;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import mmcorej.CMMCore;
import org.micromanager.MultiStagePosition;
import org.micromanager.internal.MMStudio;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raghu
 */
public class ContScanFrame extends javax.swing.JFrame {
    private static MMStudio mm_;
    private final CMMCore core_;
    private final StagePositions stagePositions;
    private final StageCommands stageCommands;
    private int regionNum;
    private String directory;
    /**
     * Creates new form ContScanFrame
     */
    public ContScanFrame(MMStudio studio) {
        mm_ = (MMStudio) studio;
        core_ = mm_.core();
        stagePositions = new StagePositions(mm_);
        stageCommands = new StageCommands(mm_);
        regionNum = 0;
        directory = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        startTitle = new javax.swing.JLabel();
        startDescription = new javax.swing.JLabel();
        setupComboBox = new javax.swing.JComboBox<>();
        beginButton = new javax.swing.JButton();
        regionsPanel = new javax.swing.JPanel();
        regionTitle = new javax.swing.JLabel();
        regionLabel = new javax.swing.JLabel();
        goToButton = new javax.swing.JButton();
        SetButton = new javax.swing.JButton();
        xLabel = new javax.swing.JLabel();
        xField = new javax.swing.JTextField();
        yLabel = new javax.swing.JLabel();
        yField = new javax.swing.JTextField();
        zField = new javax.swing.JTextField();
        zLabel = new javax.swing.JLabel();
        previousRegionButton = new javax.swing.JButton();
        toAcquisitionButton = new javax.swing.JButton();
        nextRegionButton = new javax.swing.JButton();
        acquisitionPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        zSetupLabel = new javax.swing.JLabel();
        channelsLabel = new javax.swing.JLabel();
        regionLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        channelComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allChannelJList = new javax.swing.JList<>();
        addChannelButton = new javax.swing.JButton();
        removeChannelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        usedChannelJList = new javax.swing.JList<>();
        moveUpButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();
        GoToButton = new javax.swing.JButton();
        zStartSetButton = new javax.swing.JButton();
        zStartLabel = new javax.swing.JLabel();
        zEndLabel = new javax.swing.JLabel();
        zEndSetButton = new javax.swing.JButton();
        zEndField = new javax.swing.JTextField();
        zStartField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        stepSizeBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        directoryBox = new javax.swing.JTextField();
        saveCheck = new javax.swing.JCheckBox();
        browseButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        startAcquisitionButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        startTitle.setText("Continuous Scan Plugin");

        startDescription.setText("This plugin is used for continuous stage motion scans. Choose HTLS or CLS and click \"Begin.\"");

        setupComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLS", "HTLS" }));
        setupComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupComboBoxActionPerformed(evt);
            }
        });

        beginButton.setText("Begin");
        beginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(startTitle))
                    .addComponent(startDescription)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(beginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(startTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beginButton)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        mainPanel.add(startPanel, "startPanel");

        regionTitle.setText("Region Setup");

        regionLabel.setText("Region" + (regionNum + 1));

        goToButton.setText("Go To");
        if (stagePositions.getPositionList().getPosition(regionNum) == null) {
            goToButton.setEnabled(false);
        }
        goToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToButtonActionPerformed(evt);
            }
        });

        SetButton.setText("Set");
        SetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetButtonActionPerformed(evt);
            }
        });

        xLabel.setText("X:");

        yLabel.setText("Y:");

        zLabel.setText("Z:");

        previousRegionButton.setText("Previous Region");
        if (regionNum < 1) {
            previousRegionButton.setEnabled(false);
        }
        previousRegionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousRegionButtonActionPerformed(evt);
            }
        });

        toAcquisitionButton.setText("Finish");
        toAcquisitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAcquisitionButtonActionPerformed(evt);
            }
        });

        nextRegionButton.setText("Next Region");
        if (regionNum < 1) {
            nextRegionButton.setEnabled(false);
        }
        nextRegionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextRegionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regionsPanelLayout = new javax.swing.GroupLayout(regionsPanel);
        regionsPanel.setLayout(regionsPanelLayout);
        regionsPanelLayout.setHorizontalGroup(
            regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regionsPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regionsPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yLabel)
                            .addComponent(zLabel)
                            .addComponent(xLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(goToButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SetButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(regionsPanelLayout.createSequentialGroup()
                        .addComponent(previousRegionButton)
                        .addGap(18, 18, 18)
                        .addComponent(toAcquisitionButton)
                        .addGap(18, 18, 18)
                        .addComponent(nextRegionButton))
                    .addGroup(regionsPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regionsPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(regionLabel))
                            .addComponent(regionTitle))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        regionsPanelLayout.setVerticalGroup(
            regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regionTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regionLabel)
                .addGap(25, 25, 25)
                .addComponent(goToButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zLabel))
                .addGap(18, 18, 18)
                .addGroup(regionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toAcquisitionButton)
                    .addComponent(previousRegionButton)
                    .addComponent(nextRegionButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        mainPanel.add(regionsPanel, "regionsPanel");

        titleLabel.setText("Acquisition Setup");

        zSetupLabel.setText("Z-stack Setup");

        channelsLabel.setText("Channels");

        regionLabel1.setText("Region 1");

        jLabel3.setText("Available");

        channelComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(core_.getAvailableConfigGroups().toArray()));
        channelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Used");

        DefaultListModel allChannelModel = new DefaultListModel();
        allChannelModel.addAll(Arrays.asList(core_.getAvailableConfigs((String) channelComboBox.getSelectedItem()).toArray()));
        allChannelJList.setModel(allChannelModel);
        jScrollPane1.setViewportView(allChannelJList);

        addChannelButton.setText("Add >>");
        addChannelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChannelButtonActionPerformed(evt);
            }
        });

        removeChannelButton.setText("<< Remove");
        removeChannelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeChannelButtonActionPerformed(evt);
            }
        });

        usedChannelJList.setModel(new DefaultListModel<String>() {
        });
        jScrollPane2.setViewportView(usedChannelJList);

        moveUpButton.setText("Move Up");
        moveUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpButtonActionPerformed(evt);
            }
        });

        moveDownButton.setText("Move Down");
        moveDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownButtonActionPerformed(evt);
            }
        });

        GoToButton.setText("Go To");

        zStartSetButton.setText("Set");
        zStartSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zStartSetButtonActionPerformed(evt);
            }
        });

        zStartLabel.setText("Z-Start:");

        zEndLabel.setText("Z-End:");

        zEndSetButton.setText("Set");
        zEndSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zEndSetButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next Region");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous Region");
        previousButton.setEnabled(false);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Step Size:");

        stepSizeBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stepSizeBox.setText("1");

        jLabel2.setText("um");

        saveCheck.setText("Save?");
        saveCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCheckActionPerformed(evt);
            }
        });

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Display?");

        startAcquisitionButton.setText("Start Acquisition");
        startAcquisitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAcquisitionButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Back To Region Setup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout acquisitionPanelLayout = new javax.swing.GroupLayout(acquisitionPanel);
        acquisitionPanel.setLayout(acquisitionPanelLayout);
        acquisitionPanelLayout.setHorizontalGroup(
            acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(titleLabel))
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GoToButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(zSetupLabel)
                                        .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(regionLabel1))))
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                            .addComponent(previousButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nextButton))
                                        .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(zEndLabel)
                                                .addComponent(zStartLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(zStartSetButton)
                                                .addComponent(zEndSetButton))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(zEndField)
                                                .addComponent(zStartField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(42, 42, 42)))
                                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stepSizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)))
                                .addGap(56, 56, 56)))
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removeChannelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moveDownButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moveUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addChannelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(59, 59, 59)
                                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(channelsLabel)
                                    .addComponent(channelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                        .addComponent(startAcquisitionButton)
                        .addGap(188, 188, 188))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                .addComponent(directoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                                .addComponent(saveCheck)
                                .addGap(118, 118, 118)))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acquisitionPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(207, 207, 207))))
        );
        acquisitionPanelLayout.setVerticalGroup(
            acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acquisitionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addComponent(channelsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(channelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addComponent(zSetupLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regionLabel1)))
                .addGap(5, 5, 5)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2)
                        .addGroup(acquisitionPanelLayout.createSequentialGroup()
                            .addComponent(addChannelButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removeChannelButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveUpButton)
                            .addGap(4, 4, 4)
                            .addComponent(moveDownButton)))
                    .addGroup(acquisitionPanelLayout.createSequentialGroup()
                        .addComponent(GoToButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zStartSetButton)
                            .addComponent(zStartLabel)
                            .addComponent(zStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zEndLabel)
                            .addComponent(zEndSetButton)
                            .addComponent(zEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousButton)
                            .addComponent(nextButton))
                        .addGap(18, 18, 18)
                        .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stepSizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browseButton)
                    .addComponent(directoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(acquisitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startAcquisitionButton)
                    .addComponent(jButton1))
                .addGap(27, 27, 27))
        );

        mainPanel.add(acquisitionPanel, "acquisitionPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setupComboBoxActionPerformed

    private void beginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginButtonActionPerformed
        if ((String)setupComboBox.getSelectedItem() == "HTLS"){
            try {
                core_.setPixelSizeConfig("20x");
            } catch (Exception ex) {
                Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ((String)setupComboBox.getSelectedItem() == "CLS") {
            try {
                core_.setPixelSizeConfig("40x");
            } catch (Exception ex) {
                Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "regionsPanel");
    }//GEN-LAST:event_beginButtonActionPerformed

    private void goToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToButtonActionPerformed
        MultiStagePosition region = stagePositions.getPositionList().getPosition(regionNum);
        if (region != null) {
            try {
                stageCommands.moveStage(region);
            } catch (Exception ex) {
                Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_goToButtonActionPerformed

    private void SetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetButtonActionPerformed
        try {
            stagePositions.setRegion(regionNum);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        MultiStagePosition region = stagePositions.getPositionList().getPosition(regionNum);

        xField.setText(String.valueOf(region.getX()));
        yField.setText(String.valueOf(region.getY()));
        zField.setText(String.valueOf(region.getZ()));

        toAcquisitionButton.setEnabled(true);
        nextRegionButton.setEnabled(true);
        goToButton.setEnabled(true);
    }//GEN-LAST:event_SetButtonActionPerformed

    private void previousRegionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousRegionButtonActionPerformed
        regionNum--;
        MultiStagePosition region = stagePositions.getPositionList().getPosition(regionNum);
        xField.setText(String.valueOf(region.getX()));
        yField.setText(String.valueOf(region.getY()));
        zField.setText(String.valueOf(region.getZ()));
        regionLabel.setText("Region" + (regionNum + 1));
        if (regionNum == 0) {
            previousRegionButton.setEnabled(false);
        }
        goToButton.setEnabled(true);
        nextRegionButton.setEnabled(true);
    }//GEN-LAST:event_previousRegionButtonActionPerformed

    private void toAcquisitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAcquisitionButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "acquisitionPanel");
        regionNum = 0;
    }//GEN-LAST:event_toAcquisitionButtonActionPerformed

    private void nextRegionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextRegionButtonActionPerformed
        regionNum++;
        if (stagePositions.getPositionList().getPosition(regionNum) != null) {
            MultiStagePosition region = stagePositions.getPositionList().getPosition(regionNum);
            xField.setText(String.valueOf(region.getX()));
            yField.setText(String.valueOf(region.getY()));
            zField.setText(String.valueOf(region.getZ()));
        }
        else {
            nextRegionButton.setEnabled(false);
            goToButton.setEnabled(false);
            xField.setText("");
            yField.setText("");
            zField.setText("");
        }
        regionLabel.setText("Region" + (regionNum + 1));
        previousRegionButton.setEnabled(true);
    }//GEN-LAST:event_nextRegionButtonActionPerformed

    private void channelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelComboBoxActionPerformed
        DefaultListModel allModel = (DefaultListModel) allChannelJList.getModel();
        allModel.removeAllElements();
        allModel.addAll(Arrays.asList(core_.getAvailableConfigs((String) channelComboBox.getSelectedItem()).toArray()));
        allChannelJList.setModel(allModel);

        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();
        usedModel.removeAllElements();
        usedChannelJList.setModel(usedModel);
    }//GEN-LAST:event_channelComboBoxActionPerformed

    private void addChannelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChannelButtonActionPerformed
        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();
        List<String> selectedList = allChannelJList.getSelectedValuesList();
        usedModel.addAll(selectedList);
        usedChannelJList.setModel(usedModel);

        DefaultListModel allModel =  (DefaultListModel) allChannelJList.getModel();
        for (int i=0; i < selectedList.size(); i++) {
            allModel.removeElement(selectedList.get(i));
        }
        allChannelJList.setModel(allModel);
    }//GEN-LAST:event_addChannelButtonActionPerformed

    private void removeChannelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeChannelButtonActionPerformed
        DefaultListModel allModel = (DefaultListModel) allChannelJList.getModel();
        List<String> selectedList = usedChannelJList.getSelectedValuesList();
        allModel.addAll(selectedList);
        allChannelJList.setModel(allModel);

        DefaultListModel usedModel =  (DefaultListModel) usedChannelJList.getModel();
        for (int i=0; i < selectedList.size(); i++) {
            usedModel.removeElement(selectedList.get(i));
        }
        usedChannelJList.setModel(usedModel);
    }//GEN-LAST:event_removeChannelButtonActionPerformed

    private void moveUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpButtonActionPerformed
        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();

        String movedChannel = usedChannelJList.getSelectedValue();
        int movedChannelIndex = usedChannelJList.getSelectedIndex();

        int channelAboveIndex = movedChannelIndex - 1;
        String channelAbove = (String) usedModel.getElementAt(channelAboveIndex);

        usedModel.setElementAt(channelAbove, movedChannelIndex);
        usedModel.setElementAt(movedChannel, channelAboveIndex);
        usedChannelJList.setModel(usedModel);
    }//GEN-LAST:event_moveUpButtonActionPerformed

    private void moveDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownButtonActionPerformed
        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();

        String movedChannel = usedChannelJList.getSelectedValue();
        int movedChannelIndex = usedChannelJList.getSelectedIndex();

        int channelBelowIndex = movedChannelIndex + 1;
        String channelBelow = (String) usedModel.getElementAt(channelBelowIndex);

        usedModel.setElementAt(channelBelow, movedChannelIndex);
        usedModel.setElementAt(movedChannel, channelBelowIndex);
        usedChannelJList.setModel(usedModel);
    }//GEN-LAST:event_moveDownButtonActionPerformed

    private void zStartSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zStartSetButtonActionPerformed
        try {
            stagePositions.setZStartPosition(regionNum);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        zStartField.setText(String.valueOf(stagePositions.getZStartPosition(regionNum)));
    }//GEN-LAST:event_zStartSetButtonActionPerformed

    private void zEndSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zEndSetButtonActionPerformed
        try {
            stagePositions.setZEndPosition(regionNum);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        zEndField.setText(String.valueOf(stagePositions.getZEndPosition(regionNum)));
    }//GEN-LAST:event_zEndSetButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        regionNum++;

        MultiStagePosition region = stagePositions.getPositionList().getPosition(regionNum);
        try {
            stageCommands.moveStage(region);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        regionLabel.setText("Region" + (regionNum + 1));
        zStartField.setText(String.valueOf(stagePositions.getZStartPosition(regionNum)));
        zEndField.setText(String.valueOf(stagePositions.getZEndPosition(regionNum)));

        if (regionNum == stagePositions.getPositionList().getNumberOfPositions()) {
            nextButton.setEnabled(false);
        }

        previousButton.setEnabled(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        regionNum--;

        MultiStagePosition region = stagePositions.getPositionList().getPosition(regionNum);
        try {
            stageCommands.moveStage(region);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        regionLabel.setText("Region" + (regionNum + 1));
        zStartField.setText(String.valueOf(stagePositions.getZStartPosition(regionNum)));
        zEndField.setText(String.valueOf(stagePositions.getZEndPosition(regionNum)));

        if (regionNum == 0) {
            previousButton.setEnabled(false);
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void saveCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCheckActionPerformed

    }//GEN-LAST:event_saveCheckActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.showSaveDialog(null);
        System.out.println(fileChooser.getCurrentDirectory());
        System.out.println(fileChooser.getSelectedFile());
        directory = fileChooser.getSelectedFile().getPath();
        directoryBox.setText(directory);
        directory.replace('\\','/');
    }//GEN-LAST:event_browseButtonActionPerformed

    private void startAcquisitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAcquisitionButtonActionPerformed
        DefaultListModel usedModel = (DefaultListModel) usedChannelJList.getModel();
        String[] usedChannelsArray = new String[usedModel.getSize()];
        String groupName = (String) channelComboBox.getSelectedItem();
        for (int i=0; i < usedModel.getSize(); i++) {
            usedChannelsArray[i] = (String) usedModel.getElementAt(i);
        }

        int stepSize = (int) Math.round(Double.valueOf(stepSizeBox.getText()));

        Acquisition acquisition = new Acquisition(stepSize, groupName, usedChannelsArray, stagePositions, mm_);
        try {
            acquisition.startAcquisition(directory, true, true);
        } catch (Exception ex) {
            Logger.getLogger(ContScanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_startAcquisitionButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContScanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContScanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContScanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContScanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContScanFrame(mm_).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoToButton;
    private javax.swing.JButton SetButton;
    private javax.swing.JPanel acquisitionPanel;
    private javax.swing.JButton addChannelButton;
    private javax.swing.JList<String> allChannelJList;
    private javax.swing.JButton beginButton;
    private javax.swing.JButton browseButton;
    private javax.swing.JComboBox<String> channelComboBox;
    private javax.swing.JLabel channelsLabel;
    private javax.swing.JTextField directoryBox;
    private javax.swing.JButton goToButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveUpButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextRegionButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton previousRegionButton;
    private javax.swing.JLabel regionLabel;
    private javax.swing.JLabel regionLabel1;
    private javax.swing.JLabel regionTitle;
    private javax.swing.JPanel regionsPanel;
    private javax.swing.JButton removeChannelButton;
    private javax.swing.JCheckBox saveCheck;
    private javax.swing.JComboBox<String> setupComboBox;
    private javax.swing.JButton startAcquisitionButton;
    private javax.swing.JLabel startDescription;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel startTitle;
    private javax.swing.JTextField stepSizeBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toAcquisitionButton;
    private javax.swing.JList<String> usedChannelJList;
    private javax.swing.JTextField xField;
    private javax.swing.JLabel xLabel;
    private javax.swing.JTextField yField;
    private javax.swing.JLabel yLabel;
    private javax.swing.JTextField zEndField;
    private javax.swing.JLabel zEndLabel;
    private javax.swing.JButton zEndSetButton;
    private javax.swing.JTextField zField;
    private javax.swing.JLabel zLabel;
    private javax.swing.JLabel zSetupLabel;
    private javax.swing.JTextField zStartField;
    private javax.swing.JLabel zStartLabel;
    private javax.swing.JButton zStartSetButton;
    // End of variables declaration//GEN-END:variables
}
